return {
	"stevearc/conform.nvim",
	event = { "BufWritePre" },
	cmd = { "ConformInfo" },
	opts = {
		formatters_by_ft = {
			go = { "gofmt", "golines" },
			terraform = { "terraform_fmt" },
			tf = { "terraform_fmt" },
			sh = { "shfmt", "shellcheck", "shellharden" },
			yaml = { "yamlfmt" },
			rust = { "rustfmt" },
			toml = { "taplo" },
			lua = { "stylua" },
			javascript = { "biome", "prettier", "deno_fmt", stop_after_first = true },
			typescript = { "biome", "prettier", "deno_fmt", stop_after_first = true },
			json = { "jq", "biome" },
			jsonc = { "biome" },
			css = { "biome", "prettier", stop_after_first = true },
			graphql = { "biome" },
			python = { "ruff_fix", "ruff_format", "ruff_organize_imports", "isort" },
			markdown = { "prettier" },
			ruby = { "rubyfmt" },
			html = { "prettier" },
		},
		default_format_opts = {
			lsp_format = "fallback",
		},
		format_on_save = {
			lsp_format = "fallback",
			timeout_ms = 500,
		},
		format_after_save = {
			lsp_format = "fallback",
		},
		notify_on_error = true,
		notify_no_formatters = true,
		log_level = vim.log.levels.ERROR,
	},
}
